### PR TITLE
Laravel 9.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 9.x.

**Before merging**, you need to:

- Checkout the `l9-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/timacdonald/log-fake/pull/32/commits/25dedb4c64f558f6820443632425ab7a5aa29ffe?w=1) for Laravel 9. However, you should review these changes to ensure the desired combination of versions are built for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/log-fake.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "timacdonald/log-fake": "dev-l9-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by araeuchle** [comment]
whats the stand of this package? :) 
We could really use this in our laravel 9 application :)

**Comment by timacdonald** [comment]
Will be tagging a new version shortly to support Laravel 9 etc.

**Comment by stefanzweifel** [comment]
Any update on this?

**Comment by timacdonald** [comment]
Hey folks! Sorry for the delay on this one.

I've just tagged a 2.0 RC that supports Laravel 9 and has a plethora of new features and assertions. The upgrade for everyone I'm hoping will be a noop and not involve any breaking changes.

See: https://github.com/timacdonald/log-fake/releases/tag/2.0.0-rc1

Will tag a stable 2.0 within the week. Let me know any feedback if you take the RC for a spin.

Gonna close this PR and track things over in this issue: https://github.com/timacdonald/log-fake/issues/34

**Pull request closed without merging**
